function widget = defineCallbacks(widget)
%defineCallbacks - List of callback declarations for ERWiN.
%   defineCallbacks(widget) - takes blank widget structure and returns it
%   with updated callbacks.
%
%   Created by J.P.Monney - H.N.L (UNIGE)
%   Last Update: 03/05/2022


% ---------------------- Electrode Parameter Panel ---------------------- %

widget.params.spinner_NumElectrodes.ValueChangedFcn         = ...
    {@numElectrodeChanged,widget};
widget.params.dropdown_ElectrodeSelector.ValueChangedFcn    = ...
    {@electrodeSelectionChanged,widget};
widget.params.radiogroup1.SelectionChangedFcn               = ...
    {@hemisphereChanged,widget};
widget.params.field_ElectrodeName.ValueChangedFcn           = ...
    {@electrodeNameChanged,widget};
widget.params.field_NumContacts.ValueChangedFcn             = ...
    {@numContactsChanged,widget};
widget.params.field_ContactDistance.ValueChangedFcn         = ...
    {@contactDistChanged, widget};
widget.params.field_XDeepest.ValueChangedFcn                = ...
    {@deepCoordsChanged, widget};
widget.params.field_YDeepest.ValueChangedFcn                = ...
    {@deepCoordsChanged, widget};
widget.params.field_ZDeepest.ValueChangedFcn                = ...
    {@deepCoordsChanged, widget};
widget.params.button_PickDeepest.ButtonPushedFcn            = ...
    {@pickButtonPush, widget};
widget.params.field_XSecond.ValueChangedFcn                 = ...
    {@secondCoordsChanged, widget};
widget.params.field_YSecond.ValueChangedFcn                 = ...
    {@secondCoordsChanged, widget};
widget.params.field_ZSecond.ValueChangedFcn                 = ...
    {@secondCoordsChanged, widget};
widget.params.button_PickSecond.ButtonPushedFcn             = ...
    {@pickButtonPush, widget};
widget.params.button_estimate.ButtonPushedFcn               = ...
    {@estimateButtonPush, widget};


% ------------------- Slice viewer Glassbrain callbacks ----------------- %

%%% TABS PANEL
widget.panel_CentralTabsMRI.SelectionChangedFcn             = ...
    {@viewerChanged, widget};

%%% CT TAB
widget.button_selectNifti_CT.ButtonPushedFcn                = ...
    {@selectFile, widget};
widget.field_Xvalue_CT.ValueChangedFcn                      = ...
    {@fieldValueChanged, widget};
widget.field_Yvalue_CT.ValueChangedFcn                      = ...
    {@fieldValueChanged, widget};
widget.field_Zvalue_CT.ValueChangedFcn                      = ...
    {@fieldValueChanged, widget};
widget.slider_X_CT.ValueChangingFcn                         = ...
    {@sliderValueChanging, widget};
widget.slider_Y_CT.ValueChangingFcn                         = ...
    {@sliderValueChanging, widget};
widget.slider_Z_CT.ValueChangingFcn                         = ...
    {@sliderValueChanging, widget};
widget.slider_X_CT.ValueChangedFcn                          = ...
    {@sliderValueChanging, widget};
widget.slider_Y_CT.ValueChangedFcn                          = ...
    {@sliderValueChanging, widget};
widget.slider_Z_CT.ValueChangedFcn                          = ...
    {@sliderValueChanging, widget};
widget.button_smallerX_CT.ButtonPushedFcn                   = ...
    {@smallerButtonPush, widget};
widget.button_smallerY_CT.ButtonPushedFcn                   = ...
    {@smallerButtonPush, widget};
widget.button_smallerZ_CT.ButtonPushedFcn                   = ...
    {@smallerButtonPush, widget};
widget.button_greaterX_CT.ButtonPushedFcn                   = ...
    {@greaterButtonPush, widget};
widget.button_greaterY_CT.ButtonPushedFcn                   = ...
    {@greaterButtonPush, widget};
widget.button_greaterZ_CT.ButtonPushedFcn                   = ...
    {@greaterButtonPush, widget};
widget.slider_contacts_CT.ValueChangedFcn                   = ...
    {@contactSliderValueChanging,widget};
widget.button_correctContacts.ButtonPushedFcn               = ...
    {@contactCorrect, widget};

%%% T1 TAB
widget.button_selectNifti_T1.ButtonPushedFcn                = ...
    {@selectFile, widget};
widget.field_Xvalue_T1.ValueChangedFcn                      = ...
    {@field_valueChanged, widget};
widget.field_Yvalue_T1.ValueChangedFcn                      = ...
    {@field_valueChanged, widget};
widget.field_Zvalue_T1.ValueChangedFcn                      = ...
    {@field_valueChanged, widget};
widget.slider_X_T1.ValueChangingFcn                         = ...
    {@sliderValueChanging, widget};
widget.slider_Y_T1.ValueChangingFcn                         = ...
    {@sliderValueChanging, widget};
widget.slider_Z_T1.ValueChangingFcn                         = ...
    {@sliderValueChanging, widget};
widget.slider_X_T1.ValueChangedFcn                          = ...
    {@sliderValueChanging, widget};
widget.slider_Y_T1.ValueChangedFcn                          = ...
    {@sliderValueChanging, widget};
widget.slider_Z_T1.ValueChangedFcn                          = ...
    {@sliderValueChanging, widget};
widget.button_smallerX_T1.ButtonPushedFcn                   = ...
    {@smallerButtonPush, widget};
widget.button_smallerY_T1.ButtonPushedFcn                   = ...
    {@smallerButtonPush, widget};
widget.button_smallerZ_T1.ButtonPushedFcn                   = ...
    {@smallerButtonPush, widget};
widget.button_greaterX_T1.ButtonPushedFcn                   = ...
    {@greaterButtonPush, widget};
widget.button_greaterY_T1.ButtonPushedFcn                   = ...
    {@greaterButtonPush, widget};
widget.button_greaterZ_T1.ButtonPushedFcn                   = ...
    {@greaterButtonPush, widget};
widget.slider_contacts_T1.ValueChangedFcn                   = ...
    {@contactSliderValueChanging,widget};

%%% GLASSBRAIN TAB
widget.glassbrain.UserData.checkboxCT.ValueChangedFcn       = ...
    {@meshViewerChanged, widget};
widget.glassbrain.UserData.checkboxT1.ValueChangedFcn       = ...
    {@meshViewerChanged, widget};
widget.glassbrain.UserData.buttonColor.ButtonPushedFcn      = ...
     {@electrodeColorChanged, widget};
    
% ------------------------- Tree Nodes callbacks ------------------------ %
widget.tree_Summary.SelectionChangedFcn                     = ...
    {@treeSelectionChange, widget};

% ------------------------- Done Button callbacks ----------------------- %
widget.params.button_done.ButtonPushedFcn                   = ...
    {@donePushed,widget,widget.fig,widget.fig.Position};



end